image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build
  - package
  - deploy

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn package -B"
  artifacts:
    paths:
      - backend/target/*.jar

docker-build:
  stage: package
  before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

  script:
  - docker build -t registry.gitlab.com/antpas14/fantalegheev/backend:$CI_COMMIT_SHORT_SHA ./backend
  - docker push registry.gitlab.com/antpas14/fantalegheev/backend:$CI_COMMIT_SHORT_SHA

  - docker build -t registry.gitlab.com/antpas14/fantalegheev/ui:$CI_COMMIT_SHORT_SHA ./ui
  - docker push registry.gitlab.com/antpas14/fantalegheev/ui:$CI_COMMIT_SHORT_SHA

deploy:
  image: 'google/cloud-sdk:latest'
  stage: deploy
  script:
    # Authenticate with GKE
    - echo "$SERVICE_ACCOUNT_KEY" > key.json
    - gcloud auth activate-service-account --key-file=key.json
    - gcloud config set project kubernetes-254718
    - gcloud config set container/cluster standard-cluster-1
    - gcloud config set compute/zone us-central1-a
    - gcloud container clusters get-credentials standard-cluster-1 --zone us-central1-a
    # Do the deployment
    - sed s/\%TAG\%/$CI_COMMIT_SHORT_SHA/g kubernetes/deployment.yaml | kubectl apply -f -
  environment:
    name: prod
