version: '3'

services:
        fantaleghe-backend: 
                image: fantaleghe-backend
                ports: 
                        - "8100:8100"
                links:
                        - "selenium:selenium"
                depends_on:
                        - selenium
        ui:
                image: fantaleghe-ui
                ports: 
                        - "3001:3001"
                links: 
                       - "fantaleghe-backend:fantaleghe-backend"
                depends_on: 
                        - fantaleghe-backend                       
        selenium:
                image: selenium/standalone-chrome
                ports: 
                        - "4444:4444"
                environment:
                        - GRID_TIMEOUT=120
                        - GRID_MAX_SESSION=200
                        - GRID_NEW_SESSION_WAIT_TIMEOUT=-1
                        - GRID_BROWSER_TIMEOUT=120
            
