server:
  port: 8100
  servlet:
    context-path: /
logging:
  level:
    org.springframework.web: DEBUG
properties:
  calculate:
    baseUrl: "http://leghe.fantacalcio.it/"
    calendarSuffix: "/calendario"
    rankingSuffix: "/classifica"
  fetcher:
    fetcher: "http://localhost:5000"
