server:
  port: 8101
  servlet:
    context-path: /
logging:
  level:
    org.springframework.web: DEBUG
properties:
  baseUrl: "http://leghe.fantacalcio.it/"
  calendarSuffix: "/calendario"
  rankingSuffix: "/classifica"
  seleniumUrl: "http://selenium:4444/wd/hub"
