server:
  port: 8100
  servlet:
    context-path: /
logging:
  level:
    org.springframework.web: DEBUG
properties:
  baseUrl: "http://leghe.fantacalcio.com/"
  calendarSuffix: "/calendario"
  seleniumUrl: "http://127.0.0.1:4444/wd/hub"
